# Generated by Django 5.1.1 on 2024-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='age_limited',
        ),
        migrations.RemoveField(
            model_name='game',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='size',
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
